name: labeler

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
