name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          draft-pull-request: false
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"style","section":"Miscellaneous","hidden":true},{"type":"refactor","section":"Miscellaneous","hidden":true},{"type":"perf","section":"Performance Improvements","hidden":false},{"type":"test","section":"Tests","hidden":true},{"type":"build","section":"CI/CD and Build System","hidden":true},{"type":"ci","section":"CI/CD and Build System","hidden":true},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"revert","section":"Miscellaneous","hidden":true}]'
